---
# Ansible Galaxy Requirements
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: community.docker
    version: ">=3.4.0"
  - name: community.general
    version: ">=8.0.0"
  - name: community.postgresql
    version: ">=3.0.0"
  - name: ansible.posix
    version: ">=1.5.0"

roles:
  - name: geerlingguy.docker
    version: "6.1.0"
